// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Popularity struct {
	Lang      string `json:"lang"`
	Os        string `json:"os"`
	Arch      string `json:"arch"`
	Instances int32  `json:"instances"`
}

type Query struct {
}
